### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by aceexd** [juv/vibranceGUI#124]
When i installed vibrancegui it just automatically made both of my screens much greyer than before. Uninstalled and restarted PC several times and its still grey. Both of screens have digital vibrance on 50%. Im on a nvidia 1650 graphics card

**Comment by aceexd** [comment]
And on startup on my pc both of my screens become black for a second which they didnt do before

**Comment by juv** [comment]
Hi, 

if you have any weird side-effects by using vibranceGUI, you can use the "Display Driver Uninstaller" tool to entirely remove your GPU drivers and all their config files. After that you can reinstall and have a fresh.

I am not aware that other users have reported that monitors have gotten a greyish tint upon using vibranceGUI. Keep in mind that vibranceGUI is essentially automating just one single feature of your NVIDIA GPU driver: the setting for digital vibrance. When you start the vibranceGUI application, the default Windows vibrance value will be 50%. When this value is lower to whatever you have configured in your NVIDIA Control Panel before using vibranceGUI and have not changed the default value in the vibranceGUI application, it might cause your screen to look more grey because you had a higher Windows vibrance value before.

**Comment by juv** [comment]
It looks like this issue has also been reported in https://github.com/juv/vibranceGUI/issues/128 and that issue contains more information, so I am closing this one
