### ISSUE TITLE
Wonder if there is a way for laptop gpu's to be supported

### ISSUE THREAD

**Issue by bruhger12** [juv/vibranceGUI#129]
I noticed that in my nvidia control panel, That if I was using my dedicated gpu and not my integrated graphic theres a color vibrance setting, Otherwise there isnt, Maybe that could make it possible for vibrancegui to be laptop supported

**Comment by juv** [comment]
Hi, I have recently taken another look into the Nvidia API and it looks like they still separate the drivers internally for desktop GPUs and laptop GPUs. Some features are disabled in the Nvidia driver in case you have a laptop GPU. Probably it is due to legacy code in their drivers which - in the past - were necessary to prevent the laptop GPUs with lower performance to not get overloaded by the standard feature set that is generally supported for desktop GPUs. Times have changed of course and the hardware definitely is potent enough to run these features but they are simply not activated for laptop GPUs in the driver.

I'll close the issue as I do not think this will change anytime soon. Probably no one at Nvidia really cares enough to fix it.
