### ISSUE TITLE
vibrance gui saying i have both drivers on a fresh pc

### ISSUE THREAD

**Issue by goosegetsloose** [juv/vibranceGUI#135]
so i built the pc about a month ago from all new parts an yet i keep getting this message, there is no way any amd drivers couldve been installed, im extremely hesitant to use DDU just because i have no idea what im doing, if anyone has any fix for this please let me know
![31315624-538760c2-ac1c-11e7-99e7-29597d8bcb61](https://github.com/juv/vibranceGUI/assets/172970043/8fba8dfe-4468-448f-b70f-83066ce96d68)

**Comment by MetaCrawler** [comment]
https://github.com/juv/vibranceGUI/issues/67#issuecomment-452063846

Here is the soluton that works for me on Windows 11.
With using and AMD Processor / Mainboard (and respective AMD drivers) and a Nvidia GPU.
Just use the "nvidia only" or "amd only" depending on your hardware.

**Comment by juv** [comment]
> [#67 (comment)](https://github.com/juv/vibranceGUI/issues/67#issuecomment-452063846)
> 
> Here is the soluton that works for me on Windows 11. With using and AMD Processor / Mainboard (and respective AMD drivers) and a Nvidia GPU. Just use the "nvidia only" or "amd only" depending on your hardware.

Thanks for taking the time and trying to help others out. 

@goosegetsloose You find a workaround in the linked comment above.

On top of that, I want to mention that for the check to decide whether both AMD and NVIDIA driver files are on your pc or not, can not be a false positive outcome. So both drivers must be on your system. See more details about that in this comment: https://github.com/juv/vibranceGUI/issues/67#issuecomment-452061566. You can manually uninstall the not needed driver files and use the main version of the program instead of using the workaround above.
