### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by lamka02sk** [juv/vibranceGUI#21]
Make a Linux version too please.

**Comment by juvlarN** [comment]
Hi,

apparently this is not possible for NVIDIA as their NVAPI (https://developer.nvidia.com/nvapi) is for Windows platform only.

AMD might work as their ADL (http://developer.amd.com/tools-and-sdks/graphics-development/display-library-adl-sdk/) is compatible with Linux as well. But porting this over to Linux just for an AMD version is not gonna happen.

Greets

**Comment by aPollO2k** [comment]
I think it's not much work. Maybe i will try it this weekend. lamka02sk have you tried to run it with mono(-complete) ?

**Comment by lamka02sk** [comment]
No I havent. Maybe I will try...

**Comment by juvlarN** [comment]
What's the status on this issue?

**Comment by juvlarN** [comment]
Any updates?

**Comment by Firenox89** [comment]
So I just had a look into it, but ADL is still not supported for AMDGPU.
Also there is no statement from AMD when they plan to do something in that direction.
https://community.amd.com/thread/218865
So cards from the 200 series and older ones could work with catalyst drivers.
But since this project was created for Windows, Im not sure if it makes much sense to put in the effort to port everything to Linux.
For once only older AMD cards could work ATM and on the other side C# isn't exactly language of choice for Linux devs(At leased I would rather create a new project then adding it here).

**Comment by i-need-to-tell-you-something** [comment]
I don't know anything about this topic, but apparently there is now a project for similar functionality on Linux: https://github.com/zee-mzha/vibrantLinux

**Comment by tanjilk** [comment]
> I don't know anything about this topic, but apparently there is now a project for similar functionality on Linux: https://github.com/zee-mzha/vibrantLinux

its hard to install it, i just want to have an high saturation in-game specially on csgo

**Comment by Scrumplex** [comment]
As @i-need-to-tell-you-something mentioned there is an alternative for this on Linux. It's is indeed hard to install currently, which is why we will have a Flatpak on Flathub in the future. That way most major distros should be supported.

Vibrant Linux now lives at https://github.com/libvibrant/vibrantLinux
Flatpak progress is at: https://github.com/flathub/flathub/pull/2720

**Comment by juv** [comment]
Closing because a Linux version is out of scope for this project
