### ISSUE TITLE
Ability to set Windows vibrance level below 50%

### ISSUE THREAD

**Issue by kennykentaur** [juv/vibranceGUI#83]
I use a lower level than the default 50% digital vibrance in Windows, so whenever I've played a game I have to manually decrease it since vibranceGUIs settings only allow it at minimum 50%.

I tried to edit the vibranceGUI.ini and setting it to a negative value, but it didn't work.
Is this possible to implement?

**Comment by juv** [comment]
Hi, this is a duplicate issue of https://github.com/juv/vibranceGUI/issues/62. Unfortunately, this is still not possible to do for external developers. Nvidia chose to not let developers go below 50% when using the driver API for some reason. Because of the entire lack of communication from NVIDIA concerning the NVAPI, this issue can not be solved.
